# Generated by Django 3.1.4 on 2020-12-25 01:38

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('author', models.CharField(db_index=True, max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('level_hash', models.BinaryField(max_length=64, unique=True)),
                ('size', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Small'), (2, 'Medium'), (3, 'Large')], db_index=True)),
                ('difficulty', main.models.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Easy'), (2, 'Normal'), (3, 'Hard'), (4, 'Very Hard'), (5, 'Lunatic')]), db_index=True, size=8)),
                ('category', main.models.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Tutorial'), (2, 'Challenge'), (3, 'Puzzle'), (4, 'Maze'), (5, 'Environmental'), (6, 'Playground'), (7, 'Misc')]), db_index=True, size=8)),
                ('file_size', models.IntegerField()),
                ('link', models.CharField(max_length=256)),
                ('icon', models.TextField()),
                ('format', models.IntegerField()),
            ],
            options={
                'ordering': ['-levelrating__downloads', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LevelRating',
            fields=[
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.level')),
                ('downloads', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('complains', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_hash', models.BinaryField(max_length=64)),
                ('uid', models.UUIDField()),
                ('platform', models.CharField(max_length=16)),
                ('action', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Download'), (2, 'Upvote'), (3, 'Downvote'), (4, 'Complain')])),
                ('time', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.level')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('uid', 'level', 'action'), name='unique_user_rate'),
        ),
    ]
