# Generated by Django 4.0.10 on 2023-06-10 15:49

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutscene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('ending', models.BooleanField()),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('author', models.CharField(db_index=True, max_length=40)),
                ('description', models.CharField(max_length=512)),
                ('size', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Small'), (2, 'Medium'), (3, 'Large')], db_index=True)),
                ('difficulty', main.models.ChoiceBitField(choices=[(0, 'Undefined'), (1, 'Easy'), (2, 'Normal'), (3, 'Hard'), (4, 'Very Hard'), (5, 'Lunatic')], db_index=True)),
                ('category', main.models.ChoiceBitField(choices=[(0, 'Undefined'), (1, 'Tutorial'), (2, 'Challenge'), (3, 'Puzzle'), (4, 'Maze'), (5, 'Environmental'), (6, 'Playground'), (7, 'Misc')], db_index=True)),
                ('file_size', models.IntegerField()),
                ('link', models.CharField(max_length=256)),
                ('icon', models.TextField()),
                ('format', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelRating',
            fields=[
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.level')),
                ('downloads', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('complains', models.IntegerField(default=0)),
                ('enters', models.IntegerField(default=0)),
                ('exits', models.IntegerField(default=0)),
                ('power0', models.IntegerField(default=0)),
                ('power1', models.IntegerField(default=0)),
                ('power2', models.IntegerField(default=0)),
                ('power3', models.IntegerField(default=0)),
                ('power4', models.IntegerField(default=0)),
                ('power5', models.IntegerField(default=0)),
                ('power6', models.IntegerField(default=0)),
                ('power7', models.IntegerField(default=0)),
                ('power8', models.IntegerField(default=0)),
                ('power9', models.IntegerField(default=0)),
                ('power10', models.IntegerField(default=0)),
                ('power11', models.IntegerField(default=0)),
                ('power12', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('author', models.CharField(default='', max_length=40)),
                ('uid', models.UUIDField()),
                ('platform', models.CharField(max_length=16)),
                ('action', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Download'), (2, 'Upvote'), (3, 'Downvote'), (4, 'Complain'), (5, 'Cutscene'), (6, 'Ending'), (7, 'Enter'), (8, 'Exit'), (100, 'Run'), (101, 'Climb'), (102, 'Double Jump'), (103, 'High Jump'), (104, 'Eye'), (105, 'Enemy Detector'), (106, 'Umbrella'), (107, 'Hologram'), (108, 'Red Key'), (109, 'Yellow Key'), (110, 'Blue Key'), (111, 'Purple Key'), (112, 'Map')])),
                ('cutscene', models.CharField(default=None, max_length=64, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(default=None, max_length=48, null=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.level')),
            ],
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_level'),
        ),
        migrations.AddField(
            model_name='cutscene',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.level'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('uid', 'level', 'action', 'cutscene'), name='unique_user_rate'),
        ),
        migrations.AddConstraint(
            model_name='cutscene',
            constraint=models.UniqueConstraint(fields=('level', 'name', 'ending'), name='unique_cutscene'),
        ),
    ]
