# Generated by Django 4.2.2 on 2023-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelrating',
            name='approved',
        ),
        migrations.AddField(
            model_name='levelrating',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Verified'), (1, 'Hard to Verify'), (2, 'Broken'), (3, 'Almost Broken'), (4, 'Partially Playable'), (5, 'Almost Playable'), (6, 'Playable')], default=0),
        ),
    ]
