# Generated by Django 3.1.4 on 2021-01-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutscene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('ending', models.BooleanField()),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rate',
            name='unique_user_rate',
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='power9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='cutscene',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='action',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Download'), (2, 'Upvote'), (3, 'Downvote'), (4, 'Complain'), (5, 'Cutscene'), (6, 'Ending'), (100, 'Run'), (101, 'Climb'), (102, 'Double Jump'), (103, 'High Jump'), (104, 'Eye'), (105, 'Enemy Detector'), (106, 'Umbrella'), (107, 'Hologram'), (108, 'Red Key'), (109, 'Yellow Key'), (110, 'Blue Key'), (111, 'Purple Key'), (112, 'Map')]),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_level'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('uid', 'level', 'action', 'cutscene'), name='unique_user_rate'),
        ),
        migrations.AddField(
            model_name='cutscene',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.level'),
        ),
        migrations.AddConstraint(
            model_name='cutscene',
            constraint=models.UniqueConstraint(fields=('level', 'name', 'ending'), name='unique_cutscene'),
        ),
    ]
