# Generated by Django 4.2.2 on 2023-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_levelrating_approved_levelrating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='rate',
            name='action',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Download'), (2, 'Upvote'), (3, 'Downvote'), (4, 'Complain'), (5, 'Cutscene'), (6, 'Ending'), (7, 'Enter'), (8, 'Exit'), (9, 'Win Exit'), (10, 'Cheat'), (100, 'Run'), (101, 'Climb'), (102, 'Double Jump'), (103, 'High Jump'), (104, 'Eye'), (105, 'Enemy Detector'), (106, 'Umbrella'), (107, 'Hologram'), (108, 'Red Key'), (109, 'Yellow Key'), (110, 'Blue Key'), (111, 'Purple Key'), (112, 'Map')]),
        ),
    ]
