# Generated by Django 3.1.4 on 2021-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210120_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_hash',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='level_hash',
        ),
        migrations.AddField(
            model_name='levelrating',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='author',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='level',
            name='author',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
