# Generated by Django 3.1.4 on 2022-07-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210202_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AddField(
            model_name='levelrating',
            name='enters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelrating',
            name='exits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='action',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Download'), (2, 'Upvote'), (3, 'Downvote'), (4, 'Complain'), (5, 'Cutscene'), (6, 'Ending'), (7, 'Enter'), (8, 'Exit'), (100, 'Run'), (101, 'Climb'), (102, 'Double Jump'), (103, 'High Jump'), (104, 'Eye'), (105, 'Enemy Detector'), (106, 'Umbrella'), (107, 'Hologram'), (108, 'Red Key'), (109, 'Yellow Key'), (110, 'Blue Key'), (111, 'Purple Key'), (112, 'Map')]),
        ),
    ]
