# Generated by Django 4.2.2 on 2024-04-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_levelrating_completions_alter_level_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelrating',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='levelrating',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Verified'), (1, 'Unfinished'), (2, 'Broken'), (3, 'Almost Broken'), (4, 'Partially Playable'), (5, 'Almost Playable'), (6, 'Playable')], default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='action',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Download'), (2, 'Upvote'), (3, 'Downvote'), (4, 'Complain'), (5, 'Cutscene'), (6, 'Ending'), (7, 'Enter'), (8, 'Exit'), (9, 'Win Exit'), (10, 'Cheat'), (11, 'Complete'), (22, 'One star'), (24, 'Two stars'), (26, 'Three stars'), (28, 'Four stars'), (30, 'Five stars'), (100, 'Run'), (101, 'Climb'), (102, 'Double Jump'), (103, 'High Jump'), (104, 'Eye'), (105, 'Enemy Detector'), (106, 'Umbrella'), (107, 'Hologram'), (108, 'Red Key'), (109, 'Yellow Key'), (110, 'Blue Key'), (111, 'Purple Key'), (112, 'Map')]),
        ),
    ]
