# Generated by Django 4.2.2 on 2024-05-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_levelrating_backlogged_levelrating_bad_design_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelrating',
            old_name='bad_design',
            new_name='cant_progress',
        ),
        migrations.AddField(
            model_name='levelrating',
            name='level_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='action',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Download'), (2, 'Upvote'), (3, 'Downvote'), (4, 'Complain'), (5, 'Cutscene'), (6, 'Ending'), (7, 'Enter'), (8, 'Exit'), (9, 'Win Exit'), (10, 'Cheat'), (11, 'Complete'), (20, 'Clear rating'), (21, '0.5 star'), (22, 'One star'), (23, '1.5 stars'), (24, 'Two stars'), (25, '2.5 star'), (26, 'Three stars'), (27, '3.5 stars'), (28, 'Four stars'), (29, '4.5 stars'), (30, 'Five stars'), (40, 'In progress'), (41, 'Completed'), (42, 'Backlog'), (43, 'Too hard'), (44, 'Not intereseted'), (45, "Can't progress"), (46, 'Level errors'), (100, 'Run'), (101, 'Climb'), (102, 'Double Jump'), (103, 'High Jump'), (104, 'Eye'), (105, 'Enemy Detector'), (106, 'Umbrella'), (107, 'Hologram'), (108, 'Red Key'), (109, 'Yellow Key'), (110, 'Blue Key'), (111, 'Purple Key'), (112, 'Map')]),
        ),
    ]
