# Generated by Django 4.2.2 on 2025-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_bad_design_levelrating_cant_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutscene',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
